language: php
php:
  - '5.5'
  - hhvm
  #- nightly
script:
  - phpunit --debug tests/ProductTest
  - phpunit --debug tests/DeviceTest
services:
  - mysql
before_install:
  - php artisan cache:clear
  - php artisan config:cache
  - export MYSQL_PWD=
  - mysql -e 'CREATE DATABASE touchiz;'
  - gunzip < storage/touchiz.sql.gz | mysql -u root touchiz 
