language: php
php:
  - '5.5'
  - hhvm
  - nightly
script:
  - phpunit
services:
  - mysql
before_install:
  - sudo apt-get install php5-mcrypt
  - sudo php5enmod mcrypt
  - sudo service apache2 restart
  - php artisan cache:clear
  - php artisan config:cache
  - export MYSQL_PWD=
  - mysql -e 'CREATE DATABASE touchiz;'
  - gunzip < storage/touchiz.sql.gz | mysql -u root touchiz 
