language: php
php:
  - '5.5'
  - hhvm
  #- nightly
script:
  - phpunit --debug
services:
  - mysql
before_install:
  - php artisan cache:clear
  - php artisan config:cache
  - export MYSQL_PWD=
  - mysql -e 'CREATE DATABASE touchiz;'
  - gunzip < storage/touchiz.sql.gz | mysql -u root touchiz 
cache:
 directories:
  - $HOME/.composer/cache
notifications:
 email:
  recipients:
   - xanaviarta@gmail.com
  on_success: always
  on_failure: always
