language: php
php:
  - '5.5'
  #- hhvm
  #- nightly
script:
  - phpunit
services:
  - mysql
before_install:
  - php artisan cache:clear
  - php artisan config:cache
  - gunzip < storage/touchiz.sql.gz | mysql -u root -p  touchiz 
